<div class="col-sm-8 text-left">
	<h2>Tipos de aumento em porcentagem para magias e habilidades:</h2>

	<p>Combatente:	 20 PV, 10 Def, Dano 4 e Mana 5  = 9.75</p>
	<p>Conjuradores: 10 PV, Dano 1, Mana 10 e 5 Def = 6.5</p>

	<p>[dano]</p>
	<p>
		<b>comum 	</b>	- até 100%<br>
		<b>incomum 	</b>	- até 200%<br>
		<b>raro 	</b>	- até 300%<br>
		<b>lendario </b>	- até 400%<br>
		<b>mestre 	</b>	- até 500%<br>	
	</p>

	<p>[critico natural]</p>
	<p>
		<b>comum 	</b>	- até 05%<br>
		<b>incomum </b>		- até 10%<br>
		<b>raro 	</b>	- até 15%<br>
		<b>lendario </b>	- até 20%<br>
		<b>mestre 	</b>	- até 25%<br>
	</p>

	<p>[critico induzido]</p>
	<p>
		<b>comum 	</b>	- até 10%<br>
		<b>incomum 	</b>	- até 20%<br>
		<b>raro 	</b>	- até 30%<br>
		<b>lendario </b>	- até 40%<br>
		<b>mestre 	</b>	- até 50%<br>
	</p>

	<p>[defesa]</p>
	<p>
		<b>comum 	</b>	- até 100%<br>
		<b>incomum 	</b>	- até 200%<br>
		<b>raro 	</b>	- até 300%<br>
		<b>lendario </b>	- até 400%<br>
		<b>mestre 	</b>	- até 500%<br>
	</p>

	<h2>Aumento em valores fixos para magias e habilidades</h2>
	<p>[vida]</p>
	<p>
		<b>comum 	</b>	- até 200<br>
		<b>incomum 	</b>	- até 500<br>
		<b>raro 	</b>	- até 900<br>
		<b>lendario </b>	- até 1400<br>
		<b>mestre 	</b>	- até 2000<br>
	</p>

	<p>[defesa]</p>
	<p>
		<b>comum 	</b>	- até 100<br>
		<b>incomum 	</b>	- até 300<br>
		<b>raro 	</b>	- até 600<br>
		<b>lendario </b>	- até 1000<br>
		<b>mestre 	</b>	- até 1500<br>
	</p>

	<p>[dano]</p>
	<p>
		<b>comum 	</b>	- até 100<br>
		<b>incomum 	</b>	- até 300<br>
		<b>raro 	</b>	- até 600<br>
		<b>lendario </b>	- até 1000<br>
		<b>mestre 	</b>	- até 1500<br>
	</p>

	<h2>Dano fixo para magias e habilidades:</h2>
	<p>
		<b>comum 	</b>	- até 10 *nivel<br>
		<b>incomum 	</b>	- até 20 *nivel<br>
		<b>raro 	</b>	- até 30 *nivel<br>
		<b>lendario </b>	- até 40 *nivel<br>
		<b>mestre 	</b>	- até 50 *nivel<br>
	</p>

	<h2>Aumento para itens em porcentagem:</h2>
	<p>
		<b>comum 	</b>	- até 20%<br>
		<b>incomum 	</b>	- até 40%<br>
		<b>raro 	</b>	- até 60%<br>
		<b>lendario </b>	- até 80%<br>
		<b>único 	</b>	- até 100%<br>
	</p>

	<h2>Aumento de habilidades em valores fixos para itens:</h2>
	<p>
		<b>comum 	</b>	- até 7		*nivel<br>
		<b>incomum 	</b>	- até 14	*nivel<br>
		<b>raro 	</b>	- até 21	*nivel<br>
		<b>lendario </b>	- até 28	*nivel<br>
		<b>único 	</b>	- até 35	*nivel<br>
	</p>
</div>
